services:
  app:
    build: .
    container_name: ti-demand-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/ti-demand
      - JWT_SECRET=segredo_super_seguro_troque_isso_em_producao
      - NODE_ENV=production
      - CLIENT_DIST_PATH=/app/public
    depends_on:
      - mongo
    networks:
      - ti-network

  mongo:
    image: mongo:6.0
    container_name: ti-demand-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ti-network

volumes:
  mongo_data:

networks:
  ti-network:
    driver: bridge
